# Generated by Django 5.0.7 on 2024-07-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_answer_created_at_alter_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '回答', 'verbose_name_plural': '回答'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '選択内容', 'verbose_name_plural': '選択内容'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'アンケート', 'verbose_name_plural': 'アンケート'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.choice', verbose_name='選択内容'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire', verbose_name='アンケート'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='選択内容ID'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire', verbose_name='アンケート'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=40, verbose_name='選択内容'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='overview',
            field=models.CharField(max_length=200, verbose_name='アンケートの概要'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='アンケートID'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(max_length=20, verbose_name='アンケートタイトル'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
